### PR TITLE
Upgrading dependencies to support terraform 0.12.0

### LINKED ISSUE #15: incompatible with 0.12
Error: Failed to instantiate provider "dnsimple" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]

terraform -v
Terraform v0.12.0
+ provider.dnsimple v0.1.0

### PR DESCRIPTION
**Pull request by gcox**
Resolves #15

### CODE REVIEW

**Comment by gcox** [comment]
@tombuildsstuff Thanks for reviewing, the requested change has been made.

**Comment by Gurpartap** [comment]
Incredible. Looking forward to a tf-0.12 compatible release.

**Comment by mapperr** [comment]
> Incredible. Looking forward to a tf-0.12 compatible release.

Me too! : )

**Comment by Gurpartap** [comment]
tommergesstuff

**Comment by nullobject** [comment]
Need this 👍

**Comment by RonenHoffer** [comment]
Need this 👍

**Comment by gcox** [comment]
@tombuildsstuff Is there anything else I can do to speed this process along?

**Comment by weppos** [comment]
@tombuildsstuff as this PR involves packaging and not code feature, I feel more confident if someone from Hashicorp can review and manage it. I hope you don't mind if I assigned it to you.

**Comment by macedigital** [comment]
@tombuildsstuff I guess I'm not alone in saying: If there is anything that can be done to speed up this PR review in any way, I'm happy to help.

**Comment by paultyng** [comment]
@weppos this looks ok to me as an update to the modules

**Pull request merged**
